### PR TITLE
pass profile, target and vars via env vars

### PR DESCRIPTION
**Pull request by syucream**
### Problem

https://github.com/AltimateAI/vscode-dbt-power-user/issues/1340

I have a complicated dbt project requires specifying profile, target and vars explicitly on dbt-compile. So currently some features run dbt-compile (e.g. compiled sql preview, lineage) don't work.

### Solution

Allow to provide these parameters via environment variables.

### Screenshot/Demo

A picture is worth a thousand words. Please highlight the changes if applicable.

### How to test

- Steps to be followed to verify the solution or code changes
- Mention if there is any settings configuration added/changed/deleted

## Checklist

- [x] I have run this code and it appears to resolve the stated issue
- [ ] `README.md` updated and added information about my change

### CODE REVIEW

**Comment by anandgupta42** [comment]
Thanks for your contribution @syucream . We will review it soon.

**Review by mdesmet — APPROVED** [review]
LGTM, thanks for the contribution.

**Comment by anandgupta42** [comment]
@syucream, can you propose a change in the docs for this feature as well?

[docs.myaltimate.com](https://docs.myaltimate.com/)

**Comment by syucream** [comment]
@anandgupta42 Sure. Which is the doc files?

**Pull request merged**
