### PR TITLE
Fix limit bug

### PR DESCRIPTION
**Pull request by saravmajestic**
### Problem

Describe the problem you are solving. Mention the ticket/issue if applicable.

### Solution

Describe the implemented solution. Add external references if needed.

### Screenshot/Demo

A picture is worth a thousand words. Please highlight the changes if applicable.

### How to test

- Steps to be followed to verify the solution or code changes
- Mention if there is any settings configuration added/changed/deleted

## Checklist

- [ ] I have run this code and it appears to resolve the stated issue
- [ ] `README.md` updated and added information about my change

### CODE REVIEW

**Comment by craigneasbey** [comment]
@saravmajestic @mdesmet 

Why is there no information on this bug please?  Was this tested?  It appears to have caused an error as macro get_show_sql does not have sql parameters:

https://github.com/dbt-labs/dbt-adapters/blob/d23b9e8dc9fc236ce9eae5519c39b19cf758f276/dbt/include/global_project/macros/adapters/show.sql#L6

Can you please resolve?

`console.ts:137 [Extension Host] Error while getting get_show_sql macro Error: Traceback (most recent call last):
  File "c:\Users\CraigNeasbey\venv\Lib\site-packages\dbt\clients\jinja.py", line 302, in exception_handler
    yield
  File "c:\Users\CraigNeasbey\venv\Lib\site-packages\dbt\clients\jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\CraigNeasbey\venv\Lib\site-packages\jinja2\runtime.py", line 757, in __call__
    raise TypeError(
TypeError: macro 'dbt_macro__get_show_sql' takes no keyword argument 'sql'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\CraigNeasbey\.vscode\extensions\innoverio.vscode-dbt-power-user-0.42.3\dist\node_python_bridge.py", line 104, in <module>
    value = eval(_compile(data['code'], '<input>', 'eval'), _locals)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<input>", line 1, in <module>
  File "c:\Users\CraigNeasbey\.vscode\extensions\innoverio.vscode-dbt-power-user-0.42.3\dist\dbt_core_integration.py", line 661, in execute_macro
    return self.get_macro_function(macro)(kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\CraigNeasbey\venv\Lib\site-packages\dbt\adapters\base\impl.py", line 1112, in execute_macro
    result = macro_function(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\CraigNeasbey\venv\Lib\site-packages\dbt\clients\jinja.py", line 330, in __call__
    return self.call_macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\CraigNeasbey\venv\Lib\site-packages\dbt\clients\jinja.py", line 255, in call_macro
    with self.exception_handler():
  File "C:\Users\CraigNeasbey\.pyenv\pyenv-win\versions\3.11.9\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "c:\Users\CraigNeasbey\venv\Lib\site-packages\dbt\clients\jinja.py", line 304, in exception_handler
    raise CaughtMacroErrorWithNodeError(exc=e, node=self.macro)
dbt.exceptions.CaughtMacroErrorWithNodeError: Compilation Error
  macro 'dbt_macro__get_show_sql' takes no keyword argument 'sql'

	at ChildProcess.onMessage (c:\Users\CraigNeasbey\.vscode\extensions\innoverio.vscode-dbt-power-user-0.42.3\dist\extension.js:14505:184)
	at Object.onceWrapper (node:events:629:26)
	at ChildProcess.emit (node:events:514:28)
	at emit (node:internal/child_process:951:14)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)`

**Comment by saravmajestic** [comment]
@craigneasbey Thanks for pointing out. Fix for this issue is in progress.

**Comment by anandgupta42** [comment]
@craigneasbey We did test it but our tests are not comprehensive enough and don't cover all the adapters. We will work on it. Thanks for reporting the issue. We have pushed a fix. Please upgrade to 0.42.5.

**Comment by craigneasbey** [comment]
Thanks for your attention on this.  I'll upgrade and test.

**Comment by craigneasbey** [comment]
Thanks, this appears to be fixed.

**Pull request merged**
